spring:
  application:
    name: "account"
  config:
    import: "configserver:http://localhost:8071"
  cloud:
    config:
      name: account, kafka-common, common, jwt-common
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    consumer:
      properties:
        spring:
          json:
            trusted:
              packages: "*"
            use:
              type:
                headers: false

